### ISSUE TITLE
Missing releases / Need help with building the correct firmware

### ISSUE THREAD

**Issue by rbs90** [warp-more-hardware/esp32-firmware#48]
Hi, 
first of all: Nice project! I really like the idea of getting the wallbox out of that cloud-nonsense.

In the flash manual in the wiki is a link to a released firmware as a bin file, but that is not available anymore (there are absolutly no releases).

Therefore I tried to build the firmware myself (from [warp2-2.0.11](https://github.com/warp-more-hardware/esp32-firmware/releases/tag/warp2-2.0.11)):
`platformio run -e warp2`

and flashed it:
`esptool.py --chip esp32 --port /dev/ttyUSB0 write_flash -z --flash_size detect 0x1000 warp2_firmware_2_0_11_63f7358a_merged.bin`

After this the ESP hangs in an boot loop:
`rst:0x3 (SW_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
ets Jul 29 2019 12:21:46`

Did I build the firmware correctly? I have an older Evsedo branded box, the ESP reports to be an 8 MB version.

Thank you in advance!

**Comment by rbs90** [comment]
I now sucessfully flashed the firmware from the old repository: https://github.com/bs-github/esp32-firmware/releases

But still it would be nice to know how I can compile these newer versions here ;-)

**Comment by bs-github** [comment]
Hello,

sorry to say, but you did build for the wrong environment. 

`platformio run -environment warpAC011K` would be the right one.  
(see https://github.com/warp-more-hardware/esp32-firmware/blob/master/software/README.md)

Besides that, the TAG you used is from the original project and quite outdated for our fork by now.  
In general it should be fine to build from master, because we do work in feature branches and merge only stuff into master that we know (or at least think) to be not (totally) broken. 😉

And sorry for the confusion with the non existent release.

We are not yet ready to push a release, because we want the flashing of the GD firmware to be working in the release.
But we are nearly there. 🤞 

Cheers
