### ISSUE TITLE
energy_abs is growing for about 0.06kWh per hour

### ISSUE THREAD

**Issue by buddy-kilo** [warp-more-hardware/esp32-firmware#61]
Not sure whether it's related to the firmware or hardware but I noticed that energy_abs (under /meter/values) constantly growing for 0.06kWh each hour when charger is idle (vehicle not connected). I don't believe 60W is ok consumption for such a device alone. Please share your opinion whether it is normal situation with this charger (hardware current meter inaccuracy or something else).

<img width="555" alt="image" src="https://github.com/user-attachments/assets/69c1700d-f77d-413f-b0b1-64a0b54ef0a3">

**Comment by bs-github** [comment]
I'm not sure either. It could be a firmware bug or just the hardware fooling us.

What I can say for sure is that the built-in meter is very inaccurate and definitely not suitable for billing purposes. 
That said, I think it's accurate enough to be of some value. In other words, it's better than nothing, and it allows for educated guesses about energy consumption.

It's something you can use for goodwill payments between neighbours. For that purpose, you can cross-check it with the values the car provides.

Please reopen if you think this is a firmware bug. I tend to think it is not, because I would expect the values to be even more off when a car is charged - for which I have no reports.

**Comment by buddy-kilo** [comment]
At least I measured the real consumption and it is indeed very small. Less than a 5W. Still can't be sure whether it might be firmware bug or my specific hardware sensor deviation. However - it would be really useful to have possibility to offset this error in firmware settings (via dedicated adjustable variable).
